name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions: write-all
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          gradle-version: '7.6.4'

      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.6.4

      - name: Execute Gradle Test
        run: ./gradlew test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit
          fail-on-error: true
